version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - mysqldb
  mysqldb:
    image:  mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: springdockerdb
      MYSQL_USER: srinivas
      MYSQL_PASSWORD: srinivasdocker
      MYSQL_ROOT_PASSWORD: srinivasdocker
